config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get '/lists', to: 'lists#index'
  resources :lists do
    resources :bookmarks, only: [:new, :create]  # shallow: true
  end
  resources :bookmarks, only: [:destroy]
end
  #get '/bookmarks', to: 'bookmarks#new'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates_uniqueness_of :movie, scope: :list
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    has_many :bookmarks
    has_many :movies, :through => :bookmarks, :dependent => :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

    def new
      @bookmark = Bookmark.new
    end

    def create
      @bookmark = Bookmark.new(bookmark_params)
      @list = List.find(params[:list_id])
      @bookmark.list = @list

      if @bookmark.save
        redirect_to list_path(@list)
      else
        render :new
      end
    end

    def destroy
      @bookmark = Bookmark.find(params[:id])
      @bookmark.destroy
    end

      private

    def bookmark_params
      params.require(:bookmark).permit(:comment, :movie_id, :list_id)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    # @movies = Movie.all
  end
  def show
    @list = List.find(params[:id])
  end
  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
  end

  private

    def list_params
      params.require(:list).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/index.html.erb
<h1>Bookmarks</h1>
<%= link_to 'add a list', new_list_path(@list)%>

app/views/bookmarks/new.html.erb
<h1> New bookmark </h1>

app/views/layouts/_navbar.html.erb
<body>
<nav class="navbar navbar-expand-lg bg-light" id="navbar">
<a class="navbar-brand" href="#">I'm a Navbar.</a>
  <div class="collapse navbar-collapse" id="navbarNav">
     <ul class="navbar-nav">
        <li class="nav-item mx-2"><%= link_to "Home", lists_path %></li>
        <li class="nav-item mx-2"><%= link_to "New", new_list_path %></li>
      </ul>
    </div>
</nav>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%# <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      </head>

  <body>
    <%= render "layouts/navbar" %>
    <div id="main-container">
      <div class="d-inline-flex p-3 m-5 bd-highlight bg-warning rounded-3">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

<%#   %>

app/views/lists/edit.html.erb
<h1>Edit your list</h1>
<%= @list.name %>
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>

<% end %>

app/views/lists/index.html.erb
<div class="container">
  <!-- Even though this page is index.html.erb, the url will be http://localhost:3000/lists/  -->

  <h1>Movie Lists Below</h1>
  <p>Movies here</p><%= @movies %>
  <p>Lists here</p><%= @lists %>
    <div class="list-group-container">
      <% @lists.each do |list| %>

        <div class="card m-2 p-2" style="width: 250px">
          <%= image_tag("movie.jpg")%>
          <div class="card-body">
            <h5 class="card-title"><%= list.name %></h5>
            <button type="button" class="btn btn-dark m-1">
              <%= link_to "View", list_path(list.id) %>
            </button>
            <button type="button" class="btn btn-dark m-1">
              <%= link_to "Destroy", list_path(list.id), method: :delete, data: { confirm: "Are you sure?" } %>
            </button>
          </div>
        </div>
      <% end %>
    </div>
</div>

app/views/lists/new.html.erb
<div class="container">
<h1>New Movie List </h1>

  <div class="container">
    <%= simple_form_for(@list) do |f| %>
      <%= f.input :name %>
      <%= f.submit %>
      <% end %>
    <button type="button" class="btn btn-light"><%= link_to "Back", lists_path %></button>
  </div>

</div>

app/views/lists/show.html.erb
<div class="container">
    <%= @list.name %>
  <button type="button" class="btn btn-light mx-3"><%= link_to "Back", lists_path %></button>
</div>